apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: executor-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: executor-sa
  namespace: default
roleRef:
  kind: Role
  name: executor-role
  apiGroup: rbac.authorization.k8s.io
