"""
Event Types - Phase 18
"""
from enum import Enum

class EventType(str, Enum):
    # Resource Events
    CPU_WARNING = "CPU_WARNING"
    CPU_CRITICAL = "CPU_CRITICAL"
    MEMORY_WARNING = "MEMORY_WARNING"
    MEMORY_CRITICAL = "MEMORY_CRITICAL"
    DISK_WARNING = "DISK_WARNING"
    DISK_CRITICAL = "DISK_CRITICAL"
    NETWORK_WARNING = "NETWORK_WARNING"
    NETWORK_CRITICAL = "NETWORK_CRITICAL"

    # Log Events
    ERROR_DETECTED = "ERROR_DETECTED"
    FATAL_ERROR = "FATAL_ERROR"
    TIMEOUT_EXCEPTION = "TIMEOUT_EXCEPTION"

    # Kubernetes Events
    OOM_KILLED = "OOM_KILLED"
    CRASH_LOOP_BACKOFF = "CRASH_LOOP_BACKOFF"
    IMAGE_PULL_BACKOFF = "IMAGE_PULL_BACKOFF"
    FAILED_SCHEDULING = "FAILED_SCHEDULING"

    # Execution Events
    ACTION_APPROVED = "ACTION_APPROVED"
    ACTION_EXECUTED = "ACTION_EXECUTED"
    ROLLBACK_TRIGGERED = "ROLLBACK_TRIGGERED"

    # Correlated Events
    RESOURCE_EXHAUSTION = "RESOURCE_EXHAUSTION"
    APPLICATION_OVERLOAD = "APPLICATION_OVERLOAD"
    NODE_FAILURE = "NODE_FAILURE"
